name: Test Custom Action

on:
  workflow_dispatch:  # Trigger manually via GitHub UI

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use custom action from the root
        uses: ../action.yml  
        with:
          URL: "https://github.com/Alluxio/alluxio/commit/9aeefcd8120bb3b89cdb437d8c32d2ed84b8a825"
          screenshot: "MaxFreeAllocator"
